import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
import { parseMarkdownBank } from "@/lib/question-import/markdown-parser";
import { questionHash } from "@/lib/security";

export async function POST(request:Request){const admin=await requireAdmin();const body=await request.json();const content=String(body.content??"");const fileName=String(body.fileName??"questions.md").slice(0,200);if(!content||content.length>5_000_000)return NextResponse.json({error:"File kosong atau melebihi 5 MB."},{status:400});const parsed=parseMarkdownBank(content);const hashes=parsed.questions.map(q=>questionHash(q.text));const ids=parsed.questions.map(q=>q.externalId).filter((id):id is string=>Boolean(id));const existing=await db.question.findMany({where:{OR:[{normalizedHash:{in:hashes}},{externalId:{in:ids}}]},select:{normalizedHash:true,externalId:true}});const duplicateSet=new Set(existing.flatMap(q=>[q.normalizedHash,q.externalId].filter(Boolean)));const duplicates=parsed.questions.filter(q=>duplicateSet.has(questionHash(q.text))||(q.externalId&&duplicateSet.has(q.externalId))).length;const preview={total:parsed.questions.length+parsed.issues.filter(i=>i.level==="error").length,valid:parsed.questions.length-duplicates,warnings:parsed.issues.filter(i=>i.level==="warning").length,invalid:parsed.issues.filter(i=>i.level==="error").length,duplicates,issues:parsed.issues.slice(0,100)};if(body.action!=="import")return NextResponse.json(preview);
  const policy=body.duplicatePolicy??"SKIP";let imported=0,skipped=0,failed=0,replaced=0;const history=await db.questionImport.create({data:{fileName,status:"PREVIEW",totalCount:preview.total,validCount:preview.valid,warningCount:preview.warnings,adminId:admin.id}});
  for(const q of parsed.questions){try{const hash=questionHash(q.text);const duplicate=await db.question.findFirst({where:{OR:[{normalizedHash:hash},...(q.externalId?[{externalId:q.externalId}]:[])]}});if(duplicate&&policy==="SKIP"){skipped++;await db.questionImportItem.create({data:{importId:history.id,externalId:q.externalId,questionText:q.text,status:"DUPLICATE",message:"Dilewati sesuai kebijakan aman."}});continue;}const material=await db.material.upsert({where:{name:q.material},create:{name:q.material},update:{}});const topic=q.topic?(await db.topic.findFirst({where:{materialId:material.id,parentId:null,name:q.topic}})??await db.topic.create({data:{materialId:material.id,name:q.topic}})):null;const data={externalId:duplicate&&policy==="IMPORT_NEW"?null:q.externalId,normalizedHash:duplicate&&policy==="IMPORT_NEW"?questionHash(`${q.text} ${Date.now()}`):hash,materialId:material.id,topicId:topic?.id,text:q.text,explanation:q.explanation,difficulty:q.difficulty,imageUrl:q.imageUrl,source:fileName,updatedById:admin.id,options:{create:q.options.map((o,index)=>({text:o.text,isCorrect:o.isCorrect,sortOrder:index}))}};if(duplicate&&policy==="REPLACE"){await db.$transaction([db.questionOption.deleteMany({where:{questionId:duplicate.id}}),db.question.update({where:{id:duplicate.id},data})]);replaced++;}else{await db.question.create({data:{...data,createdById:admin.id}});imported++;}await db.questionImportItem.create({data:{importId:history.id,externalId:q.externalId,questionText:q.text,status:duplicate?"REPLACED":"IMPORTED"}});}catch(error){failed++;await db.questionImportItem.create({data:{importId:history.id,externalId:q.externalId,questionText:q.text,status:"FAILED",message:error instanceof Error?error.message:"Unknown error"}});}}
  await db.questionImport.update({where:{id:history.id},data:{status:failed?"PARTIAL":"COMPLETED",importedCount:imported+replaced,skippedCount:skipped,failedCount:failed,completedAt:new Date()}});return NextResponse.json({...preview,imported,skipped,replaced,failed,historyId:history.id});}
