"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Question = { id:string; orderIndex:number; question:{text:string;imageUrl?:string}; options:{id:string;text:string}[]; material:string; topic?:string; selectedOptionIds:string[]; flagged:boolean };
type Session = { token:string;participantName:string;status:string;startedAt?:string;durationMinutes:number;remainingSeconds:number;resultCode?:string|null;questions:Question[] };

export function QuizRunner({ initial }: { initial: Session }) {
  const router=useRouter(); const [questions,setQuestions]=useState(initial.questions); const [current,setCurrent]=useState(0); const [seconds,setSeconds]=useState(initial.remainingSeconds); const [saving,setSaving]=useState(false); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{const timer=setInterval(()=>setSeconds((value)=>{const next=Math.max(0,value-1);if(next===0){clearInterval(timer);void fetch(`/api/quiz/sessions/${initial.token}/submit`,{method:"POST"}).then((response)=>response.json()).then((data)=>router.replace(`/result/${data.resultCode}`));}return next;}),1000);return()=>clearInterval(timer);},[initial.token,router]);
  const question=questions[current]; const answered=questions.filter((q)=>q.selectedOptionIds.length>0).length; const flagged=questions.filter((q)=>q.flagged).length; const unanswered=questions.length-answered;
  async function persist(questionId:string,optionIds:string[],flag?:boolean){setSaving(true);setError("");setQuestions((all)=>all.map((q)=>q.id===questionId?{...q,selectedOptionIds:optionIds,flagged:flag??q.flagged}:q));try{const response=await fetch(`/api/quiz/sessions/${initial.token}/answer`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({sessionQuestionId:questionId,optionIds,flagged:flag})});if(!response.ok)throw new Error((await response.json()).error);}catch(e){setError(e instanceof Error?e.message:"Jawaban belum tersimpan.");}finally{setSaving(false);}}
  async function submit(timeout=false){if(submitting)return;if(!timeout&&!confirm(`${unanswered?`Masih ada ${unanswered} soal belum dijawab. `:""}${flagged?`${flagged} soal ditandai. `:""}Submit sekarang?`))return;setSubmitting(true);try{const response=await fetch(`/api/quiz/sessions/${initial.token}/submit`,{method:"POST"});const data=await response.json();if(!response.ok)throw new Error(data.error);router.replace(`/result/${data.resultCode}`);}catch(e){setError(e instanceof Error?e.message:"Gagal submit.");setSubmitting(false);}}
  const time=useMemo(()=>`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`,[seconds]);
  return <main><header className="topbar"><div className="container quiz-header"><div><div className="brand">MTryOut Simulator</div><small>{initial.participantName}</small></div><div className={`timer ${seconds<=300?"warning":""}`}><small style={{fontSize:11,display:"block"}}>SISA WAKTU</small>{time}</div></div></header><div className="container quiz-layout"><section className="card"><div className="muted">{question.material}{question.topic?` • ${question.topic}`:""}</div><h2 style={{marginTop:12}}>Soal {current+1} dari {questions.length}</h2><p style={{fontSize:"1.15rem",lineHeight:1.7}}>{question.question.text}</p><div className="stack">{question.options.map((option)=><label className="option" key={option.id}><input type="radio" name={question.id} checked={question.selectedOptionIds.includes(option.id)} onClick={(event)=>{if(question.selectedOptionIds.includes(option.id)){event.preventDefault();void persist(question.id,[]);}}} onChange={()=>void persist(question.id,[option.id])}/><span>{option.text}</span></label>)}</div><div style={{display:"flex",justifyContent:"space-between",gap:10,marginTop:24,flexWrap:"wrap"}}><button className="button secondary" disabled={current===0} onClick={()=>setCurrent((v)=>v-1)}>Sebelumnya</button><button className="button secondary" disabled={!question.selectedOptionIds.length} onClick={()=>void persist(question.id,[])}>Hapus Jawaban</button><button className="button secondary" onClick={()=>void persist(question.id,question.selectedOptionIds,!question.flagged)}>{question.flagged?"Hapus Tanda":"Tandai Soal"}</button><button className="button" disabled={current===questions.length-1} onClick={()=>setCurrent((v)=>v+1)}>Berikutnya</button></div>{error&&<div className="notice error" style={{marginTop:16}}>{error}</div>}</section><aside className="card" style={{alignSelf:"start"}}><h3>Navigasi Soal</h3><p className="muted">{answered} dijawab • {unanswered} belum{saving?" • menyimpan…":""}</p><div className="navigator">{questions.map((q,index)=><button key={q.id} className={`nav-number ${q.selectedOptionIds.length?"answered":""} ${q.flagged?"flagged":""} ${index===current?"current":""}`} onClick={()=>setCurrent(index)}>{index+1}</button>)}</div><button className="button danger" style={{width:"100%",marginTop:20}} disabled={submitting} onClick={()=>void submit()}>{submitting?"Memproses…":"Selesaikan Latihan"}</button></aside></div></main>;
}
